"""
3D Response Surface Plots — Black-Box Polynomial Models
========================================================
Reads the fitted Black-Box polynomial coefficients from
blackbox_coefficients.csv (generated by model_regression.py)
and plots 3D response surfaces for the three mortar targets.

SP_percent is fixed at the centre-point value (0.5 %).
Experimental data points are overlaid in red.

Outputs:
  - Static PNG plots (matplotlib, 300 dpi)
  - Interactive HTML files (Plotly — rotate, zoom, pan in browser)

Author : Research Project Script
Date   : 2026-03
"""

import os
import sys
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D          # noqa: F401 (needed for 3D)
from sklearn.preprocessing import PolynomialFeatures
import plotly.graph_objects as go

# ── paths ────────────────────────────────────────────────────────────────────
ROOT_DIR    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH   = os.path.join(ROOT_DIR, "data", "data.csv")
COEFF_PATH  = os.path.join(ROOT_DIR, "output", "blackbox_coefficients.csv")
OUTPUT_DIR  = os.path.join(ROOT_DIR, "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ── load files ───────────────────────────────────────────────────────────────
for path, label in [(DATA_PATH, "data.csv"), (COEFF_PATH, "blackbox_coefficients.csv")]:
    if not os.path.isfile(path):
        sys.exit(f"[ERROR] {label} not found at:\n  {path}\n"
                 "Run model_regression.py first to generate it.")

df      = pd.read_csv(DATA_PATH)
coeff_df = pd.read_csv(COEFF_PATH)
print(f"[INFO] Loaded {len(df)} data rows and {len(coeff_df)} coefficient rows.\n")

# ── mesh grid over w_c × s_c ────────────────────────────────────────────────
WC_RANGE  = np.linspace(0.30, 0.40, 100)
SC_RANGE  = np.linspace(1.50, 3.00, 100)
WC_GRID, SC_GRID = np.meshgrid(WC_RANGE, SC_RANGE)

SP_FIXED  = 0.5        # centre-point value for SP_percent

# Flatten to build the polynomial feature matrix
wc_flat   = WC_GRID.ravel()
sc_flat   = SC_GRID.ravel()
sp_flat   = np.full_like(wc_flat, SP_FIXED)

# Build full second-order features (must mirror model_regression.py exactly)
poly = PolynomialFeatures(degree=2, include_bias=True)
grid_df = pd.DataFrame({"w_c": wc_flat, "s_c": sc_flat, "SP_percent": sp_flat})
X_grid  = poly.fit_transform(grid_df)
feat_names = poly.get_feature_names_out(grid_df.columns)

# ── helper: reconstruct coefficient vector for a target ──────────────────────
def get_coeff_vector(target_name):
    """Return coefficient array ordered to match PolynomialFeatures output."""
    sub = coeff_df[coeff_df["Target"] == target_name]
    # Map Feature name → Coefficient value
    coeff_map = dict(zip(sub["Feature"], sub["Coefficient"]))
    vec = np.array([coeff_map[f] for f in feat_names])
    return vec


# ── helper: predict on grid for a target ─────────────────────────────────────
def predict_surface(target_name):
    """Return Z surface (reshaped to grid) for a given target."""
    coefs = get_coeff_vector(target_name)
    Z_flat = X_grid @ coefs
    return Z_flat.reshape(WC_GRID.shape)


# ── helper: predict at experimental points (with SP fixed at 0.5) ────────────
def predict_at_points(target_name):
    """Predict Y for the actual experimental w_c and s_c (SP = 0.5)."""
    coefs = get_coeff_vector(target_name)
    pts_df = pd.DataFrame({
        "w_c": df["w_c"].values,
        "s_c": df["s_c"].values,
        "SP_percent": np.full(len(df), SP_FIXED)
    })
    X_pts = poly.transform(pts_df)
    return X_pts @ coefs


# ══════════════════════════════════════════════════════════════════════════════
#  PLOTTING CONFIGURATION
# ══════════════════════════════════════════════════════════════════════════════
TARGETS = [
    {
        "name": "Flow_percent",
        "z_label": "Flowability (Flow %)",
        "filename": "surface_Flow.png",
        "html_file": "surface_Flow_interactive.html",
        "cmap": "viridis",
        "plotly_cmap": "Viridis",
    },
    {
        "name": "fc28_MPa",
        "z_label": "Compressive Strength (fc28, MPa)",
        "filename": "surface_fc.png",
        "html_file": "surface_fc_interactive.html",
        "cmap": "plasma",
        "plotly_cmap": "Plasma",
    },
    {
        "name": "fr28_MPa",
        "z_label": "Flexural Strength (fr28, MPa)",
        "filename": "surface_fr.png",
        "html_file": "surface_fr_interactive.html",
        "cmap": "inferno",
        "plotly_cmap": "Inferno",
    },
]

for tgt in TARGETS:
    target_name = tgt["name"]
    print(f"Generating surface for {target_name} …")

    Z_surface = predict_surface(target_name)

    # Actual experimental data
    wc_exp = df["w_c"].values
    sc_exp = df["s_c"].values
    z_exp  = df[target_name].values

    # ── figure ───────────────────────────────────────────────────────────
    fig = plt.figure(figsize=(10, 7.5))
    ax  = fig.add_subplot(111, projection="3d")

    # Surface
    surf = ax.plot_surface(
        WC_GRID, SC_GRID, Z_surface,
        cmap=tgt["cmap"], alpha=0.75, edgecolor="none",
        antialiased=True, rstride=2, cstride=2)

    # Experimental scatter
    ax.scatter(
        wc_exp, sc_exp, z_exp,
        c="red", s=60, marker="o", edgecolors="darkred",
        linewidths=0.8, zorder=10, label="Experimental data")

    # Labels & title
    ax.set_xlabel("\nWater / Cement Ratio (w/c)", fontsize=11, labelpad=10)
    ax.set_ylabel("\nSand / Cement Ratio (s/c)", fontsize=11, labelpad=10)
    ax.set_zlabel(f"\n{tgt['z_label']}", fontsize=11, labelpad=10)
    ax.set_title(
        f"Response Surface — {tgt['z_label']}\n(SP% fixed at {SP_FIXED}%)",
        fontsize=13, fontweight="bold", pad=18)

    ax.legend(loc="upper left", fontsize=9)

    # Colour bar
    fig.colorbar(surf, ax=ax, shrink=0.45, aspect=12, pad=0.10,
                 label=tgt["z_label"])

    # Camera angle
    ax.view_init(elev=28, azim=225)

    plt.tight_layout()
    save_path = os.path.join(OUTPUT_DIR, tgt["filename"])
    fig.savefig(save_path, dpi=300)
    plt.close(fig)
    print(f"  ✓ Saved PNG  → {save_path}")

    # ── interactive Plotly HTML ───────────────────────────────────────
    fig_3d = go.Figure()

    # Down-sample the grid to keep HTML file size reasonable (every 2nd point)
    step = 2
    fig_3d.add_trace(go.Surface(
        x=WC_GRID[::step, ::step],
        y=SC_GRID[::step, ::step],
        z=Z_surface[::step, ::step],
        colorscale=tgt["plotly_cmap"],
        opacity=0.85,
        colorbar=dict(title=tgt["z_label"], len=0.6),
        name="Predicted Surface",
        showlegend=True,
    ))

    fig_3d.add_trace(go.Scatter3d(
        x=wc_exp, y=sc_exp, z=z_exp,
        mode="markers",
        marker=dict(size=5, color="red", line=dict(width=1, color="darkred")),
        name="Experimental Data",
    ))

    fig_3d.update_layout(
        title=dict(
            text=f"Response Surface — {tgt['z_label']}<br><sup>(SP% fixed at {SP_FIXED}%)</sup>",
            font=dict(size=16),
        ),
        scene=dict(
            xaxis_title="Water / Cement Ratio (w/c)",
            yaxis_title="Sand / Cement Ratio (s/c)",
            zaxis_title=tgt["z_label"],
        ),
        legend=dict(x=0.01, y=0.99),
        margin=dict(l=10, r=10, t=60, b=10),
        template="plotly_white",
    )

    html_path = os.path.join(OUTPUT_DIR, tgt["html_file"])
    fig_3d.write_html(html_path, include_plotlyjs=True)
    print(f"  ✓ Saved HTML → {html_path}")

print("\n" + "=" * 60)
print(" ALL DONE — static PNGs + interactive HTMLs saved in 'output'.")
print("=" * 60)
